environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

build: off

install:
    - "%PYTHON%\\python.exe -m pip install tox"

test_script:
    - "%PYTHON%\\python.exe -m tox -- -v -k tests/core/test_runner_results.py"

on_failure:
    - appveyor PushArtifact ".tox\\core_logger\\core_logger.log"
