environment:
    matrix:
        - PYTHON: "C:\\Python27"
          DJANGO: "1.7"
        - PYTHON: "C:\\Python27"
          DJANGO: "1.8"
        - PYTHON: "C:\\Python27"
          DJANGO: "1.9"
        - PYTHON: "C:\\Python27"
          DJANGO: "1.10"
        - PYTHON: "C:\\Python27"
          DJANGO: "1.11"
build: off

install:
    - "%PYTHON%\\python.exe -m pip install tox"

test_script:
    - '%PYTHON%\\python.exe -c "import sys; print sys.platform"'
    - "%PYTHON%\\Scripts\\tox.exe -e win32-py2.7-django%DJANGO%"

on_failure:
    - appveyor PushArtifact "%userprofile%\\.rotest\\core_logger\\core_logger.log"
