environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

build: off

init:
    - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
    - "%PYTHON%\\python.exe -m pip install tox"

test_script:
    - "%PYTHON%\\python.exe -m tox"

artifacts:
    - path: .tox/core_logger/core_logger.log
