environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

build: off

install:
    - "%PYTHON%\\python.exe -m pip install tox"

test_script:
    - '%PYTHON%\\python.exe -c "import sys; print sys.platform"'
    - "%PYTHON%\\Scripts\\tox.exe -e py27-win32 -- -v --timeout=60"

on_failure:
    - appveyor PushArtifact ".tox\\core_logger\\core_logger.log"
