environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

build: off

install:
    - "%PYTHON%\\python.exe -m pip install tox pypiwin32"

test_script:
    - "%PYTHON%\\Scripts\\tox.exe -- -v --timeout=60"

on_failure:
    - appveyor PushArtifact ".tox\\core_logger\\core_logger.log"
